# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║           EMOTES DO JEFFÃO BOT — LISTA COMPLETA + CONFIGURAÇÃO             ║
# ╠══════════════════════════════════════════════════════════════════════════════╣
# ║  Este arquivo é a FONTE DE VERDADE para todos os emotes do bot.            ║
# ║  Edite aqui para mudar nomes, IDs ou durações. O main.py lê tudo daqui.   ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
#
# FORMATO:  ("nome_digitavel", "id-do-highrise", duração_em_segundos)
#
# REGRAS DE DURAÇÃO:
#  • idle/sit (deitar, sentar): valor ≈ 0.8s ANTES do fim real → avatar nunca levanta
#  • emotes curtos (dança, gesto): tempo real da animação
#  • O código desconta latência de rede automaticamente
#
# COMO REMOVER: NÃO delete — adicione o número ao BLOCKED_EMOTE_NUMS no main.py
# ═══════════════════════════════════════════════════════════════════════════════

MAX_EMOTE_TIME = 99999

EMOTE_REAL_DURATIONS = {
    # Emojis
    "emoji-angry":      5.76,
    "emoji-celebrate":  3.41,
    "emoji-cursing":    2.38,
    "emoji-flex":       2.10,
    "emoji-gagging":    5.50,
    "emoji-thumbsup":   2.70,
    "emoji-there":      5.00,
    "emoji-sneeze":     5.50,
    "emoji-smirking":   4.00,
    "emoji-sick":       5.00,
    "emoji-scared":     5.00,
    "emoji-punch":      3.50,
    "emoji-pray":       4.00,
    "emoji-poop":       5.50,
    "emoji-naughty":    5.00,
    "emoji-mind-blown": 6.00,
    "emoji-lying":      4.50,
    "emoji-halo":       5.00,
    "emoji-hadoken":    5.00,
    "emoji-give-up":    4.00,
    "emoji-dizzy":      5.00,
    "emoji-clapping":   4.00,
    "emoji-arrogance":  5.00,
    "emoji-ghost":      6.00,
    "emoji-eyeroll":    4.50,
    # Emotes
    "emote-apart":           5.00,
    "emote-astronaut":       13.79,
    "emote-attention":       5.00,
    "emote-baseball":        6.00,
    "emote-boo":             7.00,
    "emote-bow":             3.34,
    "emote-boxer":           5.55,
    "emote-bunnyhop":        5.00,
    "emote-celebrate":       3.41,
    "emote-celebrationstep": 3.35,
    "emote-charging":        8.02,
    "emote-cold":            6.00,
    "emote-confused":        8.58,
    "emote-creepycute":      7.90,
    "emote-curtsy":          2.42,
    "emote-cute":            6.17,
    "emote-cutesalute":      3.00,
    "emote-cutey":           3.26,
    "emote-dab":             3.00,
    "emote-deathdrop":       7.00,
    "emote-death":           8.00,
    "emote-death2":          8.00,
    "emote-disappear":       5.00,
    "emote-disco":           14.00,
    "emote-elbowbump":       4.00,
    "emote-embarrassed":     5.00,
    "emote-energyball":      7.57,
    "emote-exasperated":     5.00,
    "emote-exasperatedb":    5.00,
    "emote-fail1":           4.00,
    "emote-fail2":           5.00,
    "emote-fainting":        6.00,
    "emote-fashionista":     5.61,
    "emote-float":           8.99,
    "emote-frog":            14.55,
    "emote-frollicking":     8.00,
    "emote-frustrated":      6.00,
    "emote-gangnam":         14.00,
    "emote-ghost-idle":      16.00,
    "emote-gift":            5.00,
    "emote-gordonshuffle":   10.00,
    "emote-graceful":        12.00,
    "emote-gravity":         8.95,
    "emote-greedy":          4.64,
    "emote-handstand":       5.00,
    "emote-happy":           4.00,
    "emote-harlemshake":     10.00,
    "emote-headball":        6.00,
    "emote-headblowup":      11.67,
    "emote-heartfingers":    4.50,
    "emote-hearteyes":       5.00,
    "emote-heartshape":      6.00,
    "emote-hello":           2.73,
    "emote-hero":            5.00,
    "emote-hot":             4.35,
    "emote-howl":            9.00,
    "emote-hug":             5.50,
    "emote-hugyourself":     6.00,
    "emote-hyped":           7.49,
    "emote-iceskating":      7.30,
    "emote-jetpack":         9.00,
    "emote-judochop":        4.00,
    "emote-jumpb":           3.00,
    "emote-kawaiigogo":      8.00,
    "emote-kicking":         4.87,
    "emote-kiss":            2.39,
    "emote-kissing-bound":   4.50,
    "emote-launch":          9.40,
    "emote-laughing":        2.69,
    "emote-laughing2":       5.20,
    "emote-levelup":         10.00,
    "emote-lust":            4.65,
    "emote-maniac":          4.91,
    "emote-model":           6.49,
    "emote-monster_fail":    7.00,
    "emote-nightfever":      8.00,
    "emote-ninja":           6.00,
    "emote-ninjarun":        6.00,
    "emote-no":              2.70,
    "emote-panic":           4.00,
    "emote-peace":           3.00,
    "emote-peekaboo":        6.00,
    "emote-pose1":           2.82,
    "emote-pose3":           5.10,
    "emote-pose5":           4.62,
    "emote-pose6":           5.37,
    "emote-pose7":           4.65,
    "emote-pose8":           4.81,
    "emote-pose9":           4.50,
    "emote-pose10":          3.99,
    "emote-proposing":       8.00,
    "emote-punkguitar":      9.36,
    "emote-puppet":          8.00,
    "emote-rainbow":         8.00,
    "emote-robot":           6.00,
    "emote-rofl":            5.00,
    "emote-roll":            4.00,
    "emote-ropepull":        5.20,
    "emote-sad":             5.41,
    "emote-salute":          3.00,
    "emote-secrethandshake": 3.88,
    "emote-shrink":          6.00,
    "emote-shy":             4.48,
    "emote-shy2":            4.99,
    "emote-slap":            4.00,
    "emote-sleigh":          11.33,
    "emote-snake":           5.26,
    "emote-snowangel":       6.22,
    "emote-snowball":        5.23,
    "emote-splitsdrop":      4.47,
    "emote-stargaze":        8.00,
    "emote-stargazer":       7.32,
    "emote-suckthumb":       4.19,
    "emote-sumo":            10.87,
    "emote-superpunch":      3.75,
    "emote-superrun":        6.27,
    "emote-swordfight":      5.91,
    "emote-tapdance":        11.06,
    "emote-telekinesis":     10.49,
    "emote-teleporting":     11.77,
    "emote-theatrical":      8.59,
    "emote-think":           3.69,
    "emote-timejump":        4.01,
    "emote-tired":           4.61,
    "emote-trampoline":      7.00,
    "emote-wave":            2.69,
    "emote-wings":           13.00,
    "emote-yes":             2.56,
    "emote-zombierun":       12.92,
    # Danças
    "dance-aerobics":        10.00,
    "dance-anime":           8.47,
    "dance-blackpink":       7.15,
    "dance-breakdance":      12.00,
    "dance-creepypuppet":    6.42,
    "dance-duckwalk":        10.00,
    "dance-employee":        8.00,
    "dance-floss":           8.00,
    "dance-handsup":         9.00,
    "dance-icecream":        14.77,
    "dance-jinglebell":      10.96,
    "dance-kawai":           10.29,
    "dance-macarena":        12.21,
    "dance-martial-artist":  10.00,
    "dance-metal":           9.50,
    "dance-orangejustice":   8.00,
    "dance-pennywise":       0.65,
    "dance-pinguin":         11.58,
    "dance-robotic":         10.00,
    "dance-russian":         10.25,
    "dance-sexy":            12.00,
    "dance-shoppingcart":    4.32,
    "dance-singleladies":    12.00,
    "dance-smoothwalk":      10.00,
    "dance-spiritual":       14.00,
    "dance-tiktok2":         10.39,
    "dance-tiktok8":         10.94,
    "dance-tiktok9":         11.89,
    "dance-tiktok10":        8.22,
    "dance-tiktok11":        11.00,
    "dance-tiktok12":        10.50,
    "dance-tiktok14":        11.50,
    "dance-touch":           11.70,
    "dance-voguehands":      12.00,
    "dance-weird":           21.56,
    "dance-wild":            20.00,
    "dance-wrong":           12.42,
    # Idles e sits (loop) — timing preciso é fundamental
    "idle-angry":            25.43,
    "idle-dance-casual":     9.08,
    "idle-dance-headbobbing": 25.37,
    "idle-dance-tiktok4":    15.50,
    "idle-dance-swinging":   13.20,
    "idle-enthusiastic":     15.94,
    "idle-fighter":          20.00,
    "idle-floorsleeping":    20.50,
    "idle-floorsleeping2":   14.00,
    "idle-guitar":           13.23,
    "idle-hero":             21.88,
    "idle-howl":             10.00,
    "idle-loop-aerobics":    8.51,
    "idle-loop-annoyed":     17.06,
    "idle-loop-happy":       18.80,
    "idle-loop-sad":         6.05,
    "idle-loop-shy":         16.47,
    "idle-loop-sitfloor":    22.32,
    "idle-loop-tapdance":    6.26,
    "idle-loop-tired":       21.96,
    "idle-lookup":           22.34,
    "idle-nervous":          21.71,
    "idle-posh":             18.00,
    "idle-sad":              16.00,
    "idle-sleep":            19.50,
    "idle-toilet":           29.00,
    "idle-uwu":              24.76,
    "idle-wild":             26.00,
    "idle_layingdown":       21.00,
    "idle_layingdown2":      18.50,
    "idle_singing":          10.26,
    "idle_zombie":           16.00,
    "sit-idle-cute":         17.06,
    "sit-open":              26.02,
    "sit-relaxed":           30.00,
}

DEFAULT_EMOTE_DURATIONS = {
    "emoji-": 6,
    "emote-": 15,
    "dance-": 22,
    "idle-":  33,
    "idle_":  33,
    "sit-":   31,
}


def get_default_duration(emote_id: str) -> float:
    if emote_id in EMOTE_REAL_DURATIONS:
        return EMOTE_REAL_DURATIONS[emote_id]
    for prefix, duration in DEFAULT_EMOTE_DURATIONS.items():
        if emote_id.startswith(prefix):
            return float(duration)
    return 15.0


# =====================================================================
# LISTA DE EMOTES — ordem original preservada para manter numeração
# =====================================================================

EMOTES_LIST = [
    # 1-10
    ("angry",        "emoji-angry",           5.76),
    ("bow",          "emote-bow",             3.34),
    ("casual",       "idle-dance-casual",     9.08),
    ("celebrate",    "emoji-celebrate",       3.41),
    ("charging",     "emote-charging",        8.02),
    ("confused",     "emote-confused",        8.58),
    ("curtsy",       "emote-curtsy",          2.42),
    ("cutey",        "emote-cutey",           3.26),
    ("snake",        "emote-snake",           5.26),
    ("cute",         "emote-cute",            6.17),
    # 11-20
    ("energy",       "emote-energyball",      7.57),
    ("enthusiastic", "idle-enthusiastic",     15.94),
    ("fashionista",  "emote-fashionista",     5.61),
    ("float",        "emote-float",           8.99),
    ("frog",         "emote-frog",            14.55),
    ("gagging",      "emoji-gagging",         5.50),
    ("gravity",      "emote-gravity",         8.95),
    ("greedy",       "emote-greedy",          4.64),
    ("hello",        "emote-hello",           2.73),
    ("hot",          "emote-hot",             4.35),
    # 21-30
    ("icecream",     "dance-icecream",        14.77),
    ("kiss",         "emote-kiss",            2.39),
    ("blackpink",    "dance-blackpink",       7.15),
    ("laughing",     "emote-laughing",        2.69),
    ("macarena",     "dance-macarena",        12.21),
    ("maniac",       "emote-maniac",          4.91),
    ("model",        "emote-model",           6.49),
    ("no",           "emote-no",              2.70),
    ("pose1",        "emote-pose1",           2.82),
    ("pose3",        "emote-pose3",           5.10),
    # 31-40
    ("pose5",        "emote-pose5",           4.62),
    ("pose6",        "emote-pose6",           5.37),
    ("pose7",        "emote-pose7",           4.65),
    ("pose8",        "emote-pose8",           4.81),
    ("pose9",        "emote-pose9",           4.50),
    ("pose10",       "emote-pose10",          3.99),
    ("attention",    "emote-attention",       5.00),
    ("punk",         "emote-punkguitar",      9.36),
    ("russian",      "dance-russian",         10.25),
    ("sad",          "emote-sad",             5.41),
    # 41-50
    ("tiktok4",      "idle-dance-tiktok4",    15.50),
    ("shopping",     "dance-shoppingcart",    4.32),
    ("shy",          "emote-shy",             4.48),
    ("sitfloor",     "idle-loop-sitfloor",    22.32),
    ("snowangel",    "emote-snowangel",       6.22),
    ("snowball",     "emote-snowball",        5.23),
    ("telekinesis",  "emote-telekinesis",     10.49),
    ("teleporting",  "emote-teleporting",     11.77),
    ("thumbsup",     "emoji-thumbsup",        2.70),
    ("tired",        "emote-tired",           4.61),
    # 51-60
    ("uwu",          "idle-uwu",              24.76),
    ("wave",         "emote-wave",            2.69),
    ("weird",        "dance-weird",           21.56),
    ("wrong",        "dance-wrong",           12.42),
    ("yes",          "emote-yes",             2.56),
    ("astronaut",    "emote-astronaut",       13.79),
    ("pennywise",    "dance-pennywise",       0.65),
    ("zombie",       "emote-zombierun",       12.92),
    ("sword",        "emote-swordfight",      5.91),
    ("singing",      "idle_singing",          10.26),
    # 61-70
    ("tiktok8",      "dance-tiktok8",         10.94),
    ("tiktok2",      "dance-tiktok2",         10.39),
    ("tiktok10",     "dance-tiktok10",        8.22),
    ("tiktok9",      "dance-tiktok9",         11.89),
    ("penguin",      "dance-pinguin",         11.58),
    ("guitar",       "idle-guitar",           13.23),
    ("stargazer",    "emote-stargazer",       7.32),
    ("boxer",        "emote-boxer",           5.55),
    ("puppet",       "dance-creepypuppet",    6.42),
    ("anime",        "dance-anime",           8.47),
    # 71-80
    ("creepycute",   "emote-creepycute",      7.90),
    ("headblowup",   "emote-headblowup",      11.67),
    ("shy2",         "emote-shy2",            4.99),
    ("celebrate2",   "emote-celebrate",       3.41),
    ("iceskating",   "emote-iceskating",      7.30),
    ("wildloop",     "idle-wild",             26.00),
    ("nervous",      "idle-nervous",          21.71),
    ("timejump",     "emote-timejump",        4.01),
    ("toilet",       "idle-toilet",           29.00),
    ("jingle",       "dance-jinglebell",      10.96),
    # 81-95
    ("hyped",        "emote-hyped",           7.49),
    ("sleigh",       "emote-sleigh",          11.33),
    ("kawai",        "dance-kawai",           10.29),
    ("touch",        "dance-touch",           11.70),
    ("repose",       "sit-relaxed",           30.00),
    ("celebration",  "emote-celebrationstep", 3.35),
    ("employee",     "dance-employee",        8.00),
    ("launch",       "emote-launch",          9.40),
    ("cutesalute",   "emote-cutesalute",      3.00),
    ("salute",       "emote-salute",          3.00),
    ("tiktok11",     "dance-tiktok11",        11.00),
    ("gift",         "emote-gift",            5.00),
    ("kissing",      "emote-kissing-bound",   4.50),
    ("wild",         "dance-wild",            20.00),
    ("howlloop",     "idle-howl",             10.00),
    # 96-114
    ("tiktok14",     "dance-tiktok14",        11.50),
    ("rest",         "sit-idle-cute",         17.06),
    ("zombieidle",   "idle_zombie",           16.00),
    ("relaxed",      "idle_layingdown2",      18.50),
    ("attentive",    "idle_layingdown",       21.00),
    ("sleepy",       "idle-sleep",            19.50),
    ("pouty",        "idle-sad",              16.00),
    ("posh",         "idle-posh",             18.00),
    ("tiredloop",    "idle-loop-tired",       21.96),
    ("taploop",      "idle-loop-tapdance",    6.26),
    ("shyloop",      "idle-loop-shy",         16.47),
    ("bummed",       "idle-loop-sad",         6.05),
    ("chillin",      "idle-loop-happy",       18.80),
    ("annoyed",      "idle-loop-annoyed",     17.06),
    ("aerobicsloop", "idle-loop-aerobics",    8.51),
    ("ponder",       "idle-lookup",           22.34),
    ("heropose",     "idle-hero",             21.88),
    ("relaxing",     "idle-floorsleeping2",   14.00),
    ("cozy",         "idle-floorsleeping",    20.50),
    # 115-120
    ("feelbeat",     "idle-dance-headbobbing", 25.37),
    ("irritated",    "idle-angry",            25.43),
    ("fly",          "emote-wings",           13.00),
    ("think",        "emote-think",           3.69),
    ("theatrical",   "emote-theatrical",      8.59),
    ("tapdance",     "emote-tapdance",        11.06),
    # 121-140
    ("superrun",     "emote-superrun",        6.27),
    ("punch",        "emote-superpunch",      3.75),
    ("sumo",         "emote-sumo",            10.87),
    ("thumbsuck",    "emote-suckthumb",       4.19),
    ("splits",       "emote-splitsdrop",      4.47),
    ("handshake",    "emote-secrethandshake", 3.88),
    ("rope",         "emote-ropepull",        5.20),
    ("roll",         "emote-roll",            4.00),
    ("rofl",         "emote-rofl",            5.00),
    ("robot",        "emote-robot",           6.00),
    ("rainbow",      "emote-rainbow",         8.00),
    ("propose",      "emote-proposing",       8.00),
    ("peekaboo",     "emote-peekaboo",        6.00),
    ("peace",        "emote-peace",           3.00),
    ("panic",        "emote-panic",           4.00),
    ("ninja",        "emote-ninjarun",        6.00),
    ("nightfever",   "emote-nightfever",      8.00),
    ("monster",      "emote-monster_fail",    7.00),
    ("levelup",      "emote-levelup",         10.00),
    ("laughing2",    "emote-laughing2",       5.20),
    # 141-160
    ("kicking",      "emote-kicking",         4.87),
    ("jump",         "emote-jumpb",           3.00),
    ("judo",         "emote-judochop",        4.00),
    ("jetpack",      "emote-jetpack",         9.00),
    ("hugyourself",  "emote-hugyourself",     6.00),
    ("hero",         "emote-hero",            5.00),
    ("headball",     "emote-headball",        6.00),
    ("harlem",       "emote-harlemshake",     10.00),
    ("happy",        "emote-happy",           4.00),
    ("handstand",    "emote-handstand",       5.00),
    ("graceful",     "emote-graceful",        12.00),
    ("gordon",       "emote-gordonshuffle",   10.00),
    ("ghost",        "emote-ghost-idle",      17.00),
    ("gangnam",      "emote-gangnam",         14.00),
    ("frollic",      "emote-frollicking",     8.00),
    ("faint",        "emote-fainting",        6.00),
    ("fail2",        "emote-fail2",           5.00),
    ("fail",         "emote-fail1",           4.00),
    ("exasperate",   "emote-exasperated",     5.00),
    ("elbow",        "emote-elbowbump",       4.00),
    # 161-180
    ("disco",        "emote-disco",           14.00),
    ("disappear",    "emote-disappear",       5.00),
    ("deathdrop",    "emote-deathdrop",       7.00),
    ("death2",       "emote-death2",          8.00),
    ("death",        "emote-death",           8.00),
    ("dab",          "emote-dab",             3.00),
    ("cold",         "emote-cold",            6.00),
    ("bunny",        "emote-bunnyhop",        5.00),
    ("boo",          "emote-boo",             7.00),
    ("baseball",     "emote-baseball",        6.00),
    ("apart",        "emote-apart",           5.00),
    ("there",        "emoji-there",           5.00),
    ("sneeze",       "emoji-sneeze",          5.50),
    ("smirk",        "emoji-smirking",        4.00),
    ("sick",         "emoji-sick",            5.00),
    ("scared",       "emoji-scared",          5.00),
    ("epunch",       "emoji-punch",           3.50),
    ("pray",         "emoji-pray",            4.00),
    ("poop",         "emoji-poop",            5.50),
    ("naughty",      "emoji-naughty",         5.00),
    # 181-200
    ("mindblow",     "emoji-mind-blown",      6.00),
    ("lying",        "emoji-lying",           4.50),
    ("halo",         "emoji-halo",            5.00),
    ("hadoken",      "emoji-hadoken",         5.00),
    ("giveup",       "emoji-give-up",         4.00),
    ("dizzy",        "emoji-dizzy",           5.00),
    ("clap",         "emoji-clapping",        4.00),
    ("arrogance",    "emoji-arrogance",       5.00),
    ("vogue",        "dance-voguehands",      12.00),
    ("spiritual",    "dance-spiritual",       14.00),
    ("smoothwalk",   "dance-smoothwalk",      10.00),
    ("ladies",       "dance-singleladies",    12.00),
    ("orange",       "dance-orangejustice",   8.00),
    ("metal",        "dance-metal",           10.50),
    ("martial",      "dance-martial-artist",  10.00),
    ("handsup",      "dance-handsup",         9.00),
    ("floss",        "dance-floss",           8.00),
    ("duckwalk",     "dance-duckwalk",        10.00),
    ("breakdance",   "dance-breakdance",      12.00),
    ("aerobics",     "dance-aerobics",        10.00),
    # 201-220
    ("embarrassed",  "emote-embarrassed",     5.00),
    ("ghost1",       "emoji-ghost",           6.00),
    ("heartshape",   "emote-heartshape",      6.00),
    ("hug",          "emote-hug",             5.50),
    ("laughing3",    "emote-laughing2",       5.20),
    ("eyeroll",      "emoji-eyeroll",         4.50),
    ("puppet2",      "emote-puppet",          8.00),
    ("sexy",         "dance-sexy",            12.00),
    ("frustrated",   "emote-frustrated",      6.00),
    ("fighter",      "idle-fighter",          20.00),
    ("laid",         "sit-open",              26.02),
    ("stargaze",     "emote-stargaze",        8.00),
    ("slap",         "emote-slap",            4.00),
    ("shrink",       "emote-shrink",          6.00),
    ("exasperate2",  "emote-exasperatedb",    5.00),
    ("hearteyes",    "emote-hearteyes",       5.00),
    ("heartfingers", "emote-heartfingers",    4.50),
    ("trampoline",   "emote-trampoline",      7.00),
    ("howl",         "emote-howl",            9.00),
    ("robot2",       "emote-robot",           6.00),
]

# =====================================================================
# Construção automática das estruturas usadas pelo bot
# =====================================================================

emote_mapping: dict = {}
EMOTES_BY_NUMBER: dict = {}

for _i, (_name, _value, _time) in enumerate(EMOTES_LIST, start=1):
    _entry = {"value": _value, "time": _time}
    emote_mapping[_name]          = _entry
    emote_mapping[str(_i)]        = _entry
    emote_mapping[_value]         = _entry
    emote_mapping[_value.lower()] = _entry
    EMOTES_BY_NUMBER[_i]          = (_name, _value, _time)

TOTAL_EMOTES = len(EMOTES_LIST)

_RANDOM_EXCLUDE_PREFIX = (
    "idle-loop-", "sit-", "idle_layingdown", "idle-sleep",
    "idle-toilet", "idle-floorsleeping", "idle-uwu",
)
secili_emote = {
    value: {"value": value, "time": time_}
    for (name, value, time_) in EMOTES_LIST
    if not any(value.startswith(p) for p in _RANDOM_EXCLUDE_PREFIX)
}

paid_emotes = {
    name: {"value": value, "time": time_}
    for (name, value, time_) in EMOTES_LIST
}
